version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7

    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt install xxd -qq
      - run: make
      - run: make check
